---

- name: Get Node Id
  command: >-
    docker info -f {% raw %}'{{ .Swarm.NodeID }}'{% endraw %}
  register: _docker_swarm_node_id
  changed_when: false
  tags:
    - docker-swarm-labels

- name: Set Node Id as Fact
  set_fact:
    docker_swarm_node_id: "{{ _docker_swarm_node_id.stdout }}"
  tags:
    - docker-swarm-labels

- name: Get all Node labels
  command: >-
    docker inspect -f {% raw %}'{{ json .Spec.Labels }}'{% endraw %}
    {{ docker_swarm_node_id }}
  register: docker_swarm_current_labels
  changed_when: false
  delegate_to: "{{ docker_swarm_primary_manager_name }}"
  delegate_facts: true
  tags:
    - docker-swarm-labels

- name: Storing the labels as Facts
  set_fact:
    docker_swarm_current_labels: >-
      {{ docker_swarm_current_labels.stdout | from_json }}
  tags:
    - docker-swarm-labels

- name: Removing all old labels
  command: >-
    docker node update --label-rm {{ item }} {{ docker_swarm_node_id }}
  delegate_to: "{{ docker_swarm_primary_manager_name }}"
  with_items: >
    {{ docker_swarm_current_labels |
        list |
        difference(docker_swarm_labels | default({}) | list) }}
  tags:
    - docker-swarm-labels

- name: Adding new labels
  command: >-
    docker node update --label-add {{ item.key }}={{ item.value }}
    {{ docker_swarm_node_id }}
  delegate_to: "{{ docker_swarm_primary_manager_name }}"
  when: >-
     (docker_swarm_current_labels[item.key] is not defined) or
     (docker_swarm_current_labels[item.key] != item.value)
  with_dict: "{{ docker_swarm_labels | default({}) }}"
  tags:
    - docker-swarm-labels
